export const data = [
    {
      entity: "CONTACT",
      displayName: "Account",
      displayNameCode: "FILTERS.CONTACT.ACCOUNT",
      column: "account.id",
      type: "LOOKUP",
      picklistName: "all_accounts",
      customOptions: null,
      isMultiSelect: true,
      isRange: false,
      isHorizontal: false,
      subEntity: null,
      id: "4adf"
    },
    {
      entity: "CONTACT",
      displayName: "Subscribed",
      displayNameCode: "FILTERS.CONTACT.SUBSCRIBED",
      column: "is_subscribed",
      type: "BOOLEAN",
      picklistName: null,
      customOptions: null,
      isMultiSelect: false,
      isRange: false,
      isHorizontal: false,
      subEntity: null,
      id: "db10"
    },
    {
      entity: "CONTACT",
      displayName: "Email",
      displayNameCode: "FILTERS.CONTACT.EMAIL",
      column: "email",
      type: "TEXT",
      picklistName: null,
      customOptions: null,
      isMultiSelect: false,
      isRange: false,
      isHorizontal: false,
      subEntity: null,
      id: "a100"
    },
    {
      entity: "CONTACT",
      displayName: "First Name",
      displayNameCode: "FILTERS.CONTACT.FIRST_NAME",
      column: "first_name",
      type: "TEXT",
      picklistName: null,
      customOptions: null,
      isMultiSelect: false,
      isRange: false,
      isHorizontal: false,
      subEntity: null,
      id: "b201"
    },
    {
      entity: "CONTACT",
      displayName: "Last Name",
      displayNameCode: "FILTERS.CONTACT.LAST_NAME",
      column: "last_name",
      type: "TEXT",
      picklistName: null,
      customOptions: null,
      isMultiSelect: false,
      isRange: false,
      isHorizontal: false,
      subEntity: null,
      id: "c302"
    },
    {
      entity: "CONTACT",
      displayName: "City",
      displayNameCode: "FILTERS.CONTACT.CITY",
      column: "city",
      type: "TEXT",
      picklistName: null,
      customOptions: null,
      isMultiSelect: false,
      isRange: false,
      isHorizontal: false,
      subEntity: null,
      id: "d403"
    },
    {
      entity: "CONTACT",
      displayName: "Country",
      displayNameCode: "FILTERS.CONTACT.COUNTRY",
      column: "country",
      type: "TEXT",
      picklistName: null,
      customOptions: null,
      isMultiSelect: false,
      isRange: false,
      isHorizontal: false,
      subEntity: null,
      id: "e504"
    },
    {
      entity: "CONTACT",
      displayName: "Date Created",
      displayNameCode: "FILTERS.CONTACT.DATE_CREATED",
      column: "created_at",
      type: "DATE",
      picklistName: null,
      customOptions: null,
      isMultiSelect: false,
      isRange: true,
      isHorizontal: false,
      subEntity: null,
      id: "f605"
    },
    {
      entity: "CONTACT",
      displayName: "Status",
      displayNameCode: "FILTERS.CONTACT.STATUS",
      column: "status",
      type: "PICKLIST",
      picklistName: "contact_status",
      customOptions: null,
      isMultiSelect: true,
      isRange: false,
      isHorizontal: false,
      subEntity: null,
      id: "g706"
    },
    {
      entity: "CONTACT",
      displayName: "Tags",
      displayNameCode: "FILTERS.CONTACT.TAGS",
      column: "tags",
      type: "MULTI_SELECT",
      picklistName: "contact_tags",
      customOptions: null,
      isMultiSelect: true,
      isRange: false,
      isHorizontal: true,
      subEntity: null,
      id: "h807"
    },
    
  ];
  